name: Elixir CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim

    steps:
    - uses: actions/checkout@v1
    - name: Run chapter 5 Tests
      run: |
        cd chap5
        mix deps.get
        mix test
    - name: Run chapter 6 Tests
      run: |
        cd chap6
        mix deps.get
        mix test

